swagger: "2.0"
info:
  title: beego Test API
  description: |
    beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /arbol/{id}:
    get:
      tags:
      - arbol
      description: |-
        Consulta el arbol por id
        <br>
      operationId: ArbolController.ConsultarArbol
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Arbol'
        "403":
          description: :id is empty
  /arbol/activar_nodo/{id}:
    put:
      tags:
      - arbol
      description: |-
        activa el nodo arbol
        <br>
      operationId: ArbolController.ActivarNodo
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /arbol/activar_plan/{id}:
    put:
      tags:
      - arbol
      description: |-
        activar el plan arbol
        <br>
      operationId: ArbolController.ActivarPlan
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /arbol/desactivar_nodo/{id}:
    delete:
      tags:
      - arbol
      description: |-
        desactiva el nodo arbol
        <br>
      operationId: ArbolController.DesactivarNodo
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /arbol/desactivar_plan/{id}:
    delete:
      tags:
      - arbol
      description: |-
        desactiva el plan arbol
        <br>
      operationId: ArbolController.DesactivarPlan
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Arbol:
    title: Arbol
    type: object
tags:
- name: arbol
  description: |
    ArbolController operations for Arbol
